name = "cloud-app"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-02-12"
account_id = "1857fd60ed4324f9896fb9bee774c0f2"